info.app.name=Calorie Service
info.app.version=1.0.7

spring.datasource.url=jdbc:postgresql://localhost:5432/NauJava
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
